services:
  pg:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart:
      - unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - './docker:/docker-entrypoint-initdb.d'

  app:
    build: .
    depends_on: 
      - pg
    restart:
      - unless-stopped
    container_name: widget-server
    ports:
      - 3000:$PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET_NAME=$CLOUDFLARE_BUCKET_NAME
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL